/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_media_MediaSt */

#ifndef _Included_com_example_media_MediaSt
#define _Included_com_example_media_MediaSt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_media_MediaSt
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_media_MediaSt_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_media_MediaSt
 * Method:    VideoDecCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_media_MediaSt_VideoDecCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_example_media_MediaSt
 * Method:    VideoDecDestroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_media_MediaSt_VideoDecDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_media_MediaSt
 * Method:    VideoDecFlush
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_media_MediaSt_VideoDecFlush
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_media_MediaSt
 * Method:    VideoDecWrite
 * Signature: (J[BIJI)I
 */
JNIEXPORT jint JNICALL Java_com_example_media_MediaSt_VideoDecWrite
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jlong, jint);

/*
 * Class:     com_example_media_MediaSt
 * Method:    VideoDecRead
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_example_media_MediaSt_VideoDecRead
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_example_media_MediaSt
 * Method:    LiveStreamCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_media_MediaSt_LiveStreamCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_example_media_MediaSt
 * Method:    LiveStreamDestroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_media_MediaSt_LiveStreamDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_media_MediaSt
 * Method:    LiveStreamWrite
 * Signature: (J[BIJI)I
 */
JNIEXPORT jint JNICALL Java_com_example_media_MediaSt_LiveStreamWrite
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jlong, jint);

/*
 * Class:     com_example_media_MediaSt
 * Method:    LiveStreamStartRecord
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_media_MediaSt_LiveStreamStartRecord
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_example_media_MediaSt
 * Method:    LiveStreamStopRecord
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_media_MediaSt_LiveStreamStopRecord
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_media_MediaSt
 * Method:    VideoExtractFrame
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_example_media_MediaSt_VideoExtractFrame
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
